USE ANGAJAT

SELECT *, 
		CONCAT((BONUS_SALARIU - PENALITATI_SALARIU),' LEI') AS PROFIT,
		DATEDIFF(YEAR,DATA_ELIBERARII,GETDATE()) AS ANI_ELIB,
		DATEDIFF(DAY,DATA_ANGAJARII,GETDATE()) AS ZILE_ANG,
		CONCAT(CONVERT(FLOAT,SALARIU/1.2),' LEI') AS MICSORARE_SAL,
		REPLACE(CONTRACTE,(SUBSTRING(CONVERT(VARCHAR(20),CONTRACTE),1,LEN(CONTRACTE)-4)),'*') AS PRIVAT
FROM ANGAJARE

SELECT 
		CONCAT(AVG(SALARIU),' LEI') AS SALARIU_MEDIU,
		CONCAT(MAX(SALARIU),' LEI') AS SALARIUL_MAXIM,
		CONCAT(SUM(SALARIU),' LEI') AS SUMA_SALARIILOR
FROM ANGAJARE

SELECT
		COUNT(PENALITATI_SALARIU) AS NUMAR_PEN
FROM ANGAJARE
		WHERE PENALITATI_SALARIU>0

SELECT 
		COUNT(BONUS_SALARIU) AS NUMAR_BONUS
FROM ANGAJARE
		WHERE BONUS_SALARIU>0
