--1) Scrie o interogare care va afişa pentru fiecare persoană câte angajări active are şi ce salariu total primeşte--

SELECT NUME, PRENUME, COUNT(ANGAJARE_ID) AS ANGAJARI_ACTIVE, SUM(SALARIU) AS SALARIU_TOTAL FROM ANGAJAT AN 
													INNER JOIN ANGAJARE A ON AN.ANGAJAT_ID = A.ANGAJAT_ID
WHERE DATA_ELIBERARII IS NULL
GROUP BY NUME, PRENUME
ORDER BY NUME DESC -- NU ESTE OBLIGATOR, L-AM UTILIZAT PENTRU COMODITATEA CITIRII--

--2) Scrie o interogare care va afişa (NPP, salariu, departament)--

SELECT NUME, PRENUME, SALARIU, DENUMIRE_DEPART FROM ANGAJAT AN
										   INNER JOIN ANGAJARE A ON AN.ANGAJAT_ID = A.ANGAJAT_ID
										   INNER JOIN DEPARTAMENT D ON D.DEPARTAMENT_ID = A.DEPARTAMENT_ID
ORDER BY NUME -- ASTA AM FACUT EU SA VIZUALIZEZ MAI USOR - NU E OBLIGATOR! --

--3) Scrie o interogare care va afişa pentru fiecare departament ce salarii se achită--
     --Să se afişeze numai acele rezultate a căror sumă depăşeşte 5000 lei--

SELECT DENUMIRE_DEPART, SALARIU FROM DEPARTAMENT D INNER JOIN ANGAJARE A ON D.DEPARTAMENT_ID = A.DEPARTAMENT_ID
WHERE SALARIU > 5000
ORDER BY DENUMIRE_DEPART ASC -- NU ESTE OBLIGATOR!!!--

--4) Scrie o interogare care va afişa persoanele de gen masculin din raioanele Criuleni și Orhei--

SELECT NUME, PRENUME, R.DENUMIRE AS RAION FROM ANGAJAT AN INNER JOIN LOC_STR LS ON LS.LOC_STR_ID = AN.LOC_STR_ID
											   INNER JOIN LOCALITATE L ON L.LOCALITATE_ID = LS.LOCALITATE_ID
											   INNER JOIN RAION R ON R.RAION_ID = L.RAION_ID
WHERE GEN = 1 AND (R.DENUMIRE = 'CRIULENI' OR R.DENUMIRE = 'ORHEI')
ORDER BY NUME DESC --DIN NOU, NU E OBLIGATOR, L-AM UTILIZAT PENTRU MINE--

--5) Scrie o interogare pentru a obţine datele angajatului ce a activat în cadrul companiei--
	 --(FNP, data angajării, data eliberării, funcţie)--

SELECT NUME, PRENUME, DATA_ANGAJARII, 
	   DATA_ELIBERARII, DENUMIRE_FUNCTIE FROM ANGAJAT AN 
										 INNER JOIN ANGAJARE A ON AN.ANGAJAT_ID = A.ANGAJAT_ID
										 INNER JOIN FUNCTIE F ON F.FUNCTIE_ID = A.FUNCTIE_ID
WHERE DATA_ELIBERARII IS NOT NULL
ORDER BY NUME --NU ESTE OBLIGATOR!!!--





