--EXTRAGEREA INFORMATIEI DIN BD. STUDIUL SELECT--
--SINTAXA--

SELECT [NUME_TABELA.]NUME_CAMP,...,[NUME_TABELA.]NUME_CAMP
FROM NUME_TABELA1, NUME_TABELA2,....

[WHERE CONDITII_PU_FUNCTII_DE_RAND]
[GROUP BY [NUME_TABELA.]NUME_CAMP,...]
	[HAVING CONDITII_PU_FUNCTII_DE_GRUP]
[ORDER BY [NUME_TABELA.]NUME_CAMP [ASC/DESC],...,[NUME_TABELA.]NUME_CAMP]

-------------------------------------------------------------------------------

SELECT PRODUCATOR+PRODUCATOR,PRODUCATOR,MODEL_ID,TIP,MODEL_ID+MODEL_ID
FROM PRODUSE

--REDENUMIREA CAMPURILOR--
SELECT PRODUCATOR+PRODUCATOR AS PROD,
PRODUCATOR,MODEL_ID,TIP,MODEL_ID+MODEL_ID AS 'MODEL MODEL' 
FROM PRODUSE
--'MODEL MODEL' ESTE O VARIANTA CE NU O VOM PUTEA PRELUCRA PE VIITOR--
--DE ACEEA TREBUIE DE SETAT CA AS + SIR CONTINUU (MODEL_MODEL)--

-------------------------------------------------------------------------------

--SA SE DETERMINE CARE AR FI PRETUL PC-URILOR CU REDUCERE DE 20%--
--SELECT * FROM PC - SELECTEAZA TOATE CAMPURILE TABELEI PC (PRIN * -ALL)
SELECT *, PRET*0.8 AS PRET_REDUS FROM PC
SELECT *, PRET-(PRET*(20.0/100)) AS PRET_REDUS,
PRET-(PRET*0.2) AS PRET_REDUS2, 20.0/100 FROM PC

-------------------------------------------------------------------------------

--CONVERSIA UNUI TIP DE DATE IN ALT TIP DE DATE--
--1) CAST(NUME_CAMP AS TIP_DATE_NOU)
--2) CONVERT(TIP_DATE_NOU, NUME_CAMP)
SELECT *, CD+CONVERT(VARCHAR(20), PRET) AS CD_PRET FROM PC

SELECT *, MODEL_ID+MODEL_ID AS SUMA, MODEL_ID*2 AS PRODUS, 
CAST(20 AS FLOAT)/100 AS IMPARTIREA, TIP+PRODUCATOR AS TIP_PROD,
CONVERT(VARCHAR(20),MODEL_ID)+' '+TIP+' '+PRODUCATOR AS MODEL_ID_PRODUCATOR
FROM PRODUSE

-------------------------------------------------------------------------------

--STUDIUL FUNCTIILOR DE RAND. FUNCTIILE DE PRELUCRARE A SIRURILOR DE CARACTERE--

--LEN(NUME_CAMP)--
SELECT *,LEN(TIP) AS LUNGIME, 
LEN (CONVERT(VARCHAR(10), MODEL_ID)) AS LEN_MODEL_ID
FROM PRODUSE

--SUBSTRING(NUME_CAMP,NR_SIMBOL_START,LUNGIMEA)--
SELECT *, SUBSTRING(TIP,2,3) AS SUBSTRING_TIP FROM PRODUSE

--UPPER(NUME_CAMP) / LOWER(NUME_CAMP)
SELECT *, LOWER(TIP) AS LOWER_TIP, UPPER(TIP) AS UPPER_TIP FROM PRODUSE

--SA SE SCRIE INTEROGAREA CARE VA TRANSFORMA CAMPUL TIP IN FELUL URMATOR :: --
--PRIMA SI ULTIMA CIFRA IN MINUSCUL, RESTUL IN MAJUSCUL

SELECT *, LOWER(SUBSTRING(TIP,1,1)) + UPPER(SUBSTRING(TIP,2,LEN(TIP)-2)) 
+ LOWER(SUBSTRING(TIP,LEN(TIP),1)) AS SARCINA
FROM PRODUSE

--REPLACE(NUME_CAMP, SIMBOL_DE_MODIFICAT, SIMBOL_NOU)--
SELECT *, REPLACE(TIP,'P','*') FROM PRODUSE

--SA SE CALCULEZE SUMA CIFRELOR DE FORMEAZA CIFRA MODEL_ID

SELECT *, (MODEL_ID / 1000) + ((MODEL_ID /100) % 10) + ((MODEL_ID / 10) % 10)
+ (MODEL_ID % 10) AS SARCINA_SUMA FROM PRODUSE 

--ALTA METODA--

/*
SELECT *,
CAST(SUBSTRING(CAST(MODEL_ID AS VARCHAR(10)),1,1) AS INT)
+ CAST(SUBSTRING(CAST(MODEL_ID AS VARCHAR(10)),2,1) AS INT)
+ CAST(SUBSTRING(CAST(MODEL_ID AS VARCHAR(10)),3,1) AS INT)
+ CAST(SUBSTRING(CAST(MODEL_ID AS VARCHAR(10)),4,1) AS INT)
AS SUMA FROM PRODUSE
*/

------------------------------------------------------------------------------------

USE DEPOZIT
SELECT *, VITEZA*0.9 AS VITEZA_NEW FROM LAPTOPURI
--SELECT = COUT--

SELECT *,
SUBSTRING(TIP,2,LEN(TIP)) AS SARCINA_1,
LOWER(TIP) AS SARCINA_LOWER,
UPPER(TIP) AS SARCINA_UPPER,
REPLACE(CONVERT(VARCHAR(2),ACTIV),'1','$') AS SARCINA_REPLACE,
LEN (CONVERT(VARCHAR(2),MODEL_ID)) AS SARCINA_LEN
FROM PRODUSE

-------------------------------------------------------------------------------





