--TEMA: STUDIUL DDL-CONTINUARE

USE XXX

--CREAREA SI GESTIONAREA TABELELOR
--CREAREA TABELEI: SINTAXA

[] - in sintaxa reprezinta un element neobligator
{} - in sintaxa reprezinta comanda SAU

(
	Nume_camp1 tip_date [constrangere]
	Nume_camp2 tip_date [constrangere]
	.....
	Nume_campN tip_date [constrangere]
)

CREATE TABLE PERSOANA
(
	NUME VARCHAR(20),
	PRENUME VARCHAR(20),
	DATA_NASTERII DATE,
	GEN BIT,
)

--ELIMINAREA TABELEI
DROP TABLE PERSOANA

--APLICAREA CONSTRANGERII NOT NULL
CREATE TABLE PERSOANA
(
	NUME VARCHAR(20) NOT NULL,
	PRENUME VARCHAR(20) NOT NULL,
	DATA_NASTERII DATE,
	GEN BIT,
)

--APLICAREA CONSTRANGERILOR CHEIE PRIMARA + UNIQUE 
CREATE TABLE PERSOANA
(
	PERSOANA_ID INT PRIMARY KEY,
	NUME VARCHAR(20) NOT NULL,
	PRENUME VARCHAR(20) NOT NULL,
	DATA_NASTERII DATE,
	GEN BIT,
)

--STABILIREA CONSTRANGERII DE AUTOINCREMENTARE
CREATE TABLE PERSOANA
(
	PERSOANA_ID INT PRIMARY KEY IDENTITY(1,1),
	NUME VARCHAR(20) NOT NULL,
	PRENUME VARCHAR(20) NOT NULL,
	DATA_NASTERII DATE,
	GEN BIT,
)

--STABILIREA CONSTRANGERII DEFAULT
CREATE TABLE PERSOANA
(
	PERSOANA_ID INT PRIMARY KEY IDENTITY(1,1),
	NUME VARCHAR(20) NOT NULL,
	PRENUME VARCHAR(20) NOT NULL,
	DATA_NASTERII DATE,
	GEN BIT,
	DATA_COMPLETARII DATE DEFAULT GETDATE(),
	ORA_COMPLETARII  TIME DEFAULT GETDATE(),
)

CREATE TABLE ADRESA
(
	ADRESA_ID INT PRIMARY KEY IDENTITY(1,1),
	PERSOANA_ID INT FOREIGN KEY REFERENCES PERSOANA(PERSOANA_ID),
	RAION VARCHAR(20),
	LOCALITATE VARCHAR(20)
)	