--TEST POPULAREA TABELELOR--

CREATE TABLE PERSOANE
(
	PERSOANE_ID INT PRIMARY KEY IDENTITY (1,1),
	NUME VARCHAR(50) NOT NULL,
	PRENUME VARCHAR(50),
	DATA_NASTERII DATE,
	GEN BIT DEFAULT 1,
	DATA_INREG DATE DEFAULT GETDATE(),
	ORA_INTREG TIME DEFAULT GETDATE(),
	DATA_ORA_INREG DATETIME DEFAULT GETDATE(),
)

CREATE TABLE ADRESA
(
	ADRESA_ID INT PRIMARY KEY IDENTITY(1,1),
	PERSOANE_ID	INT FOREIGN KEY REFERENCES PERSOANE(PERSOANE_ID),
	TIP_ADRESA BIT DEFAULT 0, -- 0-VIZA DE RESEDINTA SI 1-VIZA DE DOMICILIU
	RAION VARCHAR(30),
	LOCALITATE VARCHAR(30),
	STRADA VARCHAR(30),
	NR VARCHAR (5),
)
	
--TEMA: POPULAREA BD. STUDIUL INSTRUCTIUNILOR INSERT, UPDATE, DELETE

--STUDIUL INSERT-INSCRIEREA INFORMATIEI IN BD
--SINTAXA INSERT
INSERT INTO NUME_TABELA(CAMP1,CAMP2,...CAMP_N) VALUES(VALOAREA1,VALOAREA2,...VALOARE_N)
--NOTA: VALORILE NON-NUMERICE LE VOM INDICA PRIN INTERMEDIUL APOSTROF ''
--INFORMATIA IN TABELE SE INTRODUCE DE LA TABELA FRUNZA CATRE TABELA NOD

INSERT INTO PERSOANE(NUME,PRENUME,DATA_NASTERII,GEN)
VALUES('MIHAILOV','VALENTINA','1991-04-02',0),
	  ('JUNION','MIHAI','1999-07-01',0),
	  ('MANDALAC','EUGENIA','2000-02-03',0),

SET IDENTITY_INSERT PERSOANE ON --STOPAM AUTOINCREMENTUL--
INSERT INTO PERSOANE(PERSOANE_ID,NUME,PRENUME)
VALUES(100,'FLORIN','ION')

SET IDENTITY_INSERT PERSOANE OFF --ACTIVAM AUTOINCREMENTUL--
INSERT INTO PERSOANE(NUME,PRENUME)
VALUES('CRETU','IONELA')

SET IDENTITY_INSERT PERSOANE ON --STOPAM AUTOINCREMENTUL--
INSERT INTO PERSOANE(PERSOANE_ID,NUME,PRENUME)
VALUES(55,'CURCUBEU','')
SET IDENTITY_INSERT PERSOANE OFF --ACTIVAM AUTOINCREMENTUL--

INSERT INTO ADRESA(PERSOANE_ID,RAION,LOCALITATE,STRADA,NR)
VALUES(1,'MUN. CHISINAU','OR. CHISINAU','MIHAI EMINESCU','1'),
	  (3,'MUN. CHISINAU','OR. CRICOVA','MIHAI EMINESCU','25'),
	  (4,'MUN. CHISINAU','OR. VATRA','STRADA TEILOR','2')

INSERT INTO ADRESA(PERSOANE_ID,RAION,LOCALITATE,STRADA,NR)
VALUES(2,'MUN. BALTI','OR. BALTI','MIHAI EMINESCU','1')

--SINTAXA DE MODIFICARE A DATELOR--
UPDATE NUME_TABEL SET CAMP=VALOARE_NOUA, ... [ WHERE FILTRU ]

UPDATE ADRESA SET STRADA='STEFAN CEL MARE'
UPDATE ADRESA SET STRADA='MIHAI EMINESCU' WHERE ADRESA_ID=3
UPDATE ADRESA SET STRADA='STRADA TEILOR' WHERE ADRESA_ID=1

--ELIMINAREA DATELOR DIN TABELA--
DELETE NUME_TABELA [WHERE CONDITION]

DELETE ADRESA WHERE PERSOANE_ID=2