--RECAPITULARE--

USE DEPOZIT

--SA SE DETERMINE IMPRIMANTELE CARE INCEP CU LITERA 'L'--
SELECT TIP FROM IMPRIMANTE WHERE TIP LIKE 'L%'

--SA SE DETERMINE IMPRIMANTELE CARE AU PRETUL MAI MARE CA 2000 SI --
--CARE SUNT COLORE--
SELECT * FROM IMPRIMANTE WHERE PRET > 2000 AND COLOR='DA'

--SA SE DETERMINE IMPRIMANTELE CARE AU PRETUL < 200 SI TIPUL JET --
SELECT * FROM IMPRIMANTE WHERE NOT(PRET>200 AND TIP LIKE 'J%')

--STUDIUL INNER JOIN--
USE ANGAJAT
SELECT NUME, PRENUME, DATEDIFF(YEAR, DATA_ELIBERARII, GETDATE()) 
	AS SOMER 
FROM ANGAJARE A INNER JOIN ANGAJAT B 
ON A.ANGAJAT_ID = B.ANGAJAT_ID
WHERE (DATA_ELIBERARII IS NOT NULL)

--SINTAXA INNER JOIN--
/*
	SELECT CAMPURI
	FROM TABELA_A A INNER JOIN TABELA_B B 
	ON A.KEY = B.KEY

	SELECT CAMPURI
	FROM TABELA_A INNER JOIN TABELA_B 
	ON TABELA_A.KEY = TABELA_B.KEY
*/

--SA SE DETERMINE PRODUCATORII SI PC-URILE VANDUTE--
USE DEPOZIT
SELECT * FROM PC INNER JOIN PRODUSE P
ON PC.MODEL_ID = P.MODEL_ID
SELECT * FROM PC
SELECT * FROM PRODUSE WHERE TIP = 'PC'

--SA SE DETERMINE PRODUCATORII DE PC CU MODELELE IMPARE SI VITEZE PARE--
SELECT DISTINCT PRODUCATOR FROM PRODUSE P INNER JOIN PC
ON P.MODEL_ID = PC.MODEL_ID
WHERE PC.MODEL_ID%2=1 AND CONVERT(INT, VITEZA)%2=0

--SA SE DETERMINE PRODUCATORII DE IMPRIMANTE COLOR NON-LASER--
SELECT PRODUCATOR FROM PRODUSE P INNER JOIN IMPRIMANTE I
ON P.MODEL_ID = I.MODEL_ID
WHERE COLOR = 'DA' AND NOT I.TIP = 'LASER'

--SA SE DETERMINE SUMA COSTULUI PRODUSULUI SI NUMARUL DE PRODUSE--
--PENTRU FIECARE PRODUCATOR--

SELECT PRODUCATOR, COUNT(PC_ID) AS COUNT_PROD, SUM(PRET) AS SUMA_PRET 
FROM PRODUSE P INNER JOIN PC
ON P.MODEL_ID = PC.MODEL_ID
GROUP BY(PRODUCATOR)

USE ANGAJAT
--SA SE UNIFICE PRIN INNER JOIN TOATE TABELELE BD ANGAJAT--
SELECT * FROM ANGAJARE A INNER JOIN ANGAJAT AN ON A.ANGAJAT_ID = AN.ANGAJAT_ID
						 INNER JOIN DEPARTAMENT D ON D.DEPARTAMENT_ID = A.DEPARTAMENT_ID
						 INNER JOIN FUNCTIE F ON F.FUNCTIE_ID = A.FUNCTIE_ID
						 INNER JOIN LOC_STR LS ON LS.LOC_STR_ID = AN.LOC_STR_ID
						 INNER JOIN LOCALITATE L ON L.LOCALITATE_ID = LS.LOCALITATE_ID
						 INNER JOIN RAION RRR ON RRR.RAION_ID = L.RAION_ID
						 INNER JOIN STRADA SSS ON SSS.STRADA_ID = LS.STRADA_ID

--SA SE AFISEZE ANGAJATII SI FUNCTIILE ACESTORA--
SELECT CONCAT(NUME,' ', PRENUME) AS NPP, DENUMIRE_FUNCTIE  FROM ANGAJARE A 
						 INNER JOIN ANGAJAT AN ON A.ANGAJAT_ID = AN.ANGAJAT_ID
						 INNER JOIN FUNCTIE F ON F.FUNCTIE_ID = A.FUNCTIE_ID
WHERE DATA_ELIBERARII IS NULL
ORDER BY CONCAT(NUME,' ',PRENUME)